# -*- coding: utf-8 -*-
"""Day 1 Data visualization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1np5WLX6AHK05ufbppCs2MkIXU83u6xiN
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline

print(plt.style.available)



from numpy.random import randn, randint, uniform, sample



x= np.arange(0,10)
y= x*x
plt.title("Sine waveform")
plt.plot(x, y, color='b')
plt.show()

