# -*- coding: utf-8 -*-
"""Day 1 assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CdC69cgxZc7trr_5777wZcMMhwrK50Mh
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd 
import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline

x=[1,2,3,4,5,6,7] #days of week
y=[160,150,140,145,175,165,180] #sales
plt.plot(x,y,color='b', marker='o')
plt.show()

days = [1,2,3,4,5,6,7] #days of the week 
sales_1 = [160, 150, 140, 145, 175, 165, 180] #sales of the company 1
sales_2 = [70, 90, 160, 150, 140, 145, 175] #sales of the company 2

plt.figure(figsize=(6,5), dpi=150)
plt.plot(days, sales_1,label='sales_1',marker='o',color='b')
plt.plot(days, sales_2,label='sales_2',marker='o',color='r')
plt.title('Sales distribution',color='blue')
plt.xlabel('days of the week',color='blue')
plt.ylabel('sales',color='blue')
plt.legend(loc='upper left')
plt.grid()